import { Question } from "@/types/diagnosis";

export const questions: Question[] = [
  // ===== 経験・実績 (8問) =====
  {
    id: 1,
    category: "experience",
    text: "これまでのキャリアで最も力を入れたのはどちらに近いですか？",
    optionA: "新規事業・戦略立案・仕組みづくりなど「0→1」の仕事",
    optionB: "プロジェクト推進・チームマネジメント・現場改善など「1→10」の仕事",
    axisImpact: { axis: 1, direction: "A_positive", weight: 3 },
  },
  {
    id: 2,
    category: "experience",
    text: "データや数字を用いた分析・レポート作成の経験はどちらに近いですか？",
    optionA: "Excelやデータツールを使った分析・資料作成を日常的に行ってきた",
    optionB: "数字よりも、人との対話やヒアリングが中心の業務が多かった",
    axisImpact: { axis: 2, direction: "A_positive", weight: 2 },
  },
  {
    id: 3,
    category: "experience",
    text: "チームや組織を動かす役割について、あなたの経験は？",
    optionA: "チームリーダー・マネージャーとして複数人を束ねた経験がある",
    optionB: "個人として高い専門性を発揮するプレイヤーとして活躍してきた",
    axisImpact: { axis: 3, direction: "A_positive", weight: 3 },
  },
  {
    id: 4,
    category: "experience",
    text: "キャリアの転換点で、あなたはどちらを選んできましたか？",
    optionA: "より大きな成長・高い報酬を求めて積極的に転職・挑戦してきた",
    optionB: "安定した環境で深く専門性を磨く方を選んできた",
    axisImpact: { axis: 4, direction: "A_positive", weight: 2 },
  },
  {
    id: 5,
    category: "experience",
    text: "クライアントや上位職との折衝・提案経験はどちらに近いですか？",
    optionA: "経営層や意思決定者に対して提案・プレゼンをした経験が豊富",
    optionB: "現場担当者・チームメンバーへの説明・調整が中心だった",
    axisImpact: { axis: 1, direction: "A_positive", weight: 2 },
  },
  {
    id: 6,
    category: "experience",
    text: "課題解決のアプローチはどちらに近いですか？",
    optionA: "データ・ロジックを組み立てて「なぜ」を深掘りする",
    optionB: "関係者の感情・立場を読み取って合意形成を図る",
    axisImpact: { axis: 2, direction: "A_positive", weight: 3 },
  },
  {
    id: 7,
    category: "experience",
    text: "複数のプロジェクトやタスクを同時に管理した経験は？",
    optionA: "複数案件を並行して管理し、優先度判断や進捗管理に慣れている",
    optionB: "ひとつの案件・テーマに深く集中して成果を出すことが多かった",
    axisImpact: { axis: 3, direction: "A_positive", weight: 2 },
  },
  {
    id: 8,
    category: "experience",
    text: "これまでのキャリアで収入・ポジションの向上を意識してきましたか？",
    optionA: "年収・役職を明確な目標にして行動し、実際に上げてきた",
    optionB: "仕事の内容・やりがいを優先し、収入は結果としてついてくるもの",
    axisImpact: { axis: 4, direction: "A_positive", weight: 2 },
  },

  // ===== スキル・能力 (8問) =====
  {
    id: 9,
    category: "skill",
    text: "ロジカルシンキング・構造化思考のスキルについて自己評価は？",
    optionA: "MECEや論点整理など、論理的に問題を分解することが得意",
    optionB: "感覚・経験則で素早く判断することの方が得意",
    axisImpact: { axis: 1, direction: "A_positive", weight: 3 },
  },
  {
    id: 10,
    category: "skill",
    text: "Excelやスプレッドシートを使ったデータ分析スキルは？",
    optionA: "ピボットテーブル・VLOOKUP・統計分析など高度な使いこなしができる",
    optionB: "基本的な表計算は使えるが、高度な分析はあまり得意ではない",
    axisImpact: { axis: 2, direction: "A_positive", weight: 2 },
  },
  {
    id: 11,
    category: "skill",
    text: "資料作成・プレゼンテーションのスキルは？",
    optionA: "相手を動かす構成・デザインで説得力のある資料を作れる",
    optionB: "必要最低限の資料は作れるが、特別得意ではない",
    axisImpact: { axis: 1, direction: "A_positive", weight: 2 },
  },
  {
    id: 12,
    category: "skill",
    text: "ファシリテーション・会議進行のスキルは？",
    optionA: "議論を整理し、参加者の意見をうまく引き出して合意に導ける",
    optionB: "会議の進行よりも、自分の意見・専門知識を発揮することが得意",
    axisImpact: { axis: 3, direction: "A_positive", weight: 2 },
  },
  {
    id: 13,
    category: "skill",
    text: "英語スキル（ビジネス英語）はどの程度ですか？",
    optionA: "英語での会議・メール対応・交渉ができるレベル（TOEIC 700+相当）",
    optionB: "日常的には英語を使わず、ビジネス英語はほぼ経験がない",
    axisImpact: { axis: 4, direction: "A_positive", weight: 1 },
  },
  {
    id: 14,
    category: "skill",
    text: "業界・市場分析のスキルについては？",
    optionA: "市場規模・競合分析・トレンド調査を行い、示唆を出すことができる",
    optionB: "自分の専門領域内の知識は深いが、業界横断的な視点は弱い",
    axisImpact: { axis: 2, direction: "A_positive", weight: 2 },
  },
  {
    id: 15,
    category: "skill",
    text: "プロジェクトマネジメントのスキルは？",
    optionA: "スケジュール・リスク・ステークホルダー管理を統括した経験がある",
    optionB: "タスクを指示されて実行することの方が得意・経験が多い",
    axisImpact: { axis: 3, direction: "A_positive", weight: 3 },
  },
  {
    id: 16,
    category: "skill",
    text: "自己研鑽・スキルアップへの投資について",
    optionA: "書籍・セミナー・資格取得などに年間10万円以上投資している",
    optionB: "自己投資よりも経験・OJTでスキルを積む方が多い",
    axisImpact: { axis: 4, direction: "A_positive", weight: 1 },
  },

  // ===== 適性・好み (8問) =====
  {
    id: 17,
    category: "aptitude",
    text: "仕事で最もやりがいを感じるのはどちらですか？",
    optionA: "「なぜこの問題が起きているのか」を深掘りして答えを出すこと",
    optionB: "チームで協力して目標を達成し、みんなで喜ぶこと",
    axisImpact: { axis: 2, direction: "A_positive", weight: 3 },
  },
  {
    id: 18,
    category: "aptitude",
    text: "理想の働き方に近いのはどちらですか？",
    optionA: "高報酬・高成長を求めて激しい環境で働くこと",
    optionB: "ワークライフバランスを保ちながら着実にキャリアを積むこと",
    axisImpact: { axis: 4, direction: "A_positive", weight: 3 },
  },
  {
    id: 19,
    category: "aptitude",
    text: "チームでの役割として自然とどちらになりますか？",
    optionA: "全体方向性を示すリーダー・まとめ役",
    optionB: "特定分野で深い知識を提供するエキスパート",
    axisImpact: { axis: 3, direction: "A_positive", weight: 3 },
  },
  {
    id: 20,
    category: "aptitude",
    text: "新しい仕事・プロジェクトの始め方として近いのは？",
    optionA: "まず全体像・ゴールを定義して逆算でプランを作る",
    optionB: "まずできることから動きながら方向性を定めていく",
    axisImpact: { axis: 1, direction: "A_positive", weight: 2 },
  },
  {
    id: 21,
    category: "aptitude",
    text: "「コンサルタント」という職業のどの側面に最も惹かれますか？",
    optionA: "クライアントの課題を論理的に解決し、意思決定を支援すること",
    optionB: "クライアントと信頼関係を構築し、長期的にサポートすること",
    axisImpact: { axis: 2, direction: "A_positive", weight: 2 },
  },
  {
    id: 22,
    category: "aptitude",
    text: "キャリアの5年後のイメージはどちらに近いですか？",
    optionA: "ファームのパートナー・独立・起業など高いポジションを目指す",
    optionB: "特定領域の深い専門家として安定した地位を確立している",
    axisImpact: { axis: 4, direction: "A_positive", weight: 2 },
  },
  {
    id: 23,
    category: "aptitude",
    text: "複数の選択肢から意思決定するとき、あなたは？",
    optionA: "データ・根拠を整理して最適解を導く",
    optionB: "経験・直感・関係者の意見を総合して判断する",
    axisImpact: { axis: 2, direction: "A_positive", weight: 2 },
  },
  {
    id: 24,
    category: "aptitude",
    text: "「成功」の定義として近いのはどちらですか？",
    optionA: "年収・社会的地位など外から見える形での達成",
    optionB: "自分が誇れる仕事・スキルの習得など内側からの充実感",
    axisImpact: { axis: 4, direction: "A_positive", weight: 2 },
  },

  // ===== マインドセット (4問) =====
  {
    id: 25,
    category: "mindset",
    text: "プレッシャーのかかる局面で、あなたは？",
    optionA: "冷静に状況を分析し、論理的に対処策を考える",
    optionB: "周囲を巻き込みながらエネルギーで乗り越える",
    axisImpact: { axis: 1, direction: "A_positive", weight: 2 },
  },
  {
    id: 26,
    category: "mindset",
    text: "自分のキャリアに対する姿勢として近いのは？",
    optionA: "常に市場価値を意識し、積極的に機会を掴みに行く",
    optionB: "今の職場・関係を大切にして長期的に貢献する",
    axisImpact: { axis: 4, direction: "A_positive", weight: 3 },
  },
  {
    id: 27,
    category: "mindset",
    text: "「難しい・未知の課題」に直面したとき、あなたは？",
    optionA: "面白そうと感じてモチベーションが上がる",
    optionB: "リスクを慎重に見極めてから動く",
    axisImpact: { axis: 1, direction: "A_positive", weight: 2 },
  },
  {
    id: 28,
    category: "mindset",
    text: "組織・チームでの役割認識について",
    optionA: "自分がいなければ組織が動かないポジションに就きたい",
    optionB: "縁の下の力持ちとして、組織全体を支えることに誇りを感じる",
    axisImpact: { axis: 3, direction: "A_positive", weight: 2 },
  },
];
